services:
  - type: web
    name: pool-calculator
    env: python
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
    autoDeploy: true
